require: rubocop-rails

AllCops:
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/UniqBeforePluck:
  EnforcedStyle: aggressive

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

# Line length enforcement is dumb
Layout/LineLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Who uses underscores in numbers, anyway?
Style/NumericLiterals:
  Enabled: false
