version: '3'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - '54320:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - db_data:/var/lib/postgresql/data

  memcached:
    image: memcached
    restart: always

  web:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
      - memcached
    restart: always
# For development, use a path on your docker-host for /dev/twitarr
# This loads your host files into the container, getting updates without a rebuild.
#    volumes:
#      - ./:/srv/app
    environment:
      - 'PGHOST=db'
      - 'PGDATABASE=postgres'
      - 'PGUSER=postgres'
      - 'PGPASSWORD=postgres'

volumes:
  db_data:
