defaults: &defaults
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("DB_POOL", 4) %>
  port: <%= ENV["DB_PORT"] %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  variables:
    lock_timeout: <%= ENV.fetch("DB_LOCK_TIMEOUT", 0) %>
    statement_timeout: <%= ENV.fetch("DB_STATEMENT_TIMEOUT", 0) %>

development:
  <<: *defaults
  database: twitarr_development

test:
  <<: *defaults
  database: twitarr_test

production: &production
  <<: *defaults
  database: twitarr_production
  pool: 20

docker:
  <<: *production
