docker:
  secret_key_base: SECRET_KEY_HERE
  initial_admin_password: ADMIN_PASS_HERE

development:
  secret_key_base: SECRET_KEY_HERE
  initial_admin_password: ADMIN_PASS_HERE

test:
  secret_key_base: SECRET_KEY_HERE
  initial_admin_password: ADMIN_PASS_HERE

# Do not keep production secret key in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  initial_admin_password: ADMIN_PASS_HERE
  initial_official_password: OFFICIAL_PASS_HERE